### ISSUE TITLE
Sound Bug

### ISSUE THREAD

**Issue by 0ldi** [Hosq/BigWigs#1]
After about 2-3 announcement of Chromaggus breath, girl voice stop announces. Great Feature, fix plz

**Comment by Hosq** [comment]
fixed

**Comment by 0ldi** [comment]
And 1 more sound bug:
Victory sound (after kill bosses) triggered after killing:
```
Ancient Core Hound
Gurubashi Berserker
```
Some noising.

**Comment by Hosq** [comment]
should be fixed now
