### ISSUE TITLE
Is there a way to use this to track my dots?

### ISSUE THREAD

**Issue by nukul4r** [Hosq/BigWigs#18]
I really like the mechanics of the "emphasize" bars on this addon, i.e. as the timer approaches zero, the bar is enlarged moved to the center of the screen. I was wondering, is there any way to setup BigWigs to use it for tracking my (Warlock) dots? It would be awesome to have them integrated, so they are put into focus when they are about to run out. If no such configuration is possible, is this a functionality you would consider for a future version?

Thanks for maintaining the addon and keep up the great work!

**Comment by Hosq** [comment]
No way setup BigWigs to do it and i dont plan on implementing one
