### ISSUE TITLE
Lag = Bad Timers

### ISSUE THREAD

**Issue by Sqoops** [Hosq/BigWigs#19]
Can you make a check like 

local _, _, latency = GetNetStats()
if latency < 200 then
   send sync to other people
else 
   return
end

so people with way too high latency (>200 ms) wont screw up the timers of other people.
This happened to us on Chromaggus where one guy with extreme lag destroyed the timers.

**Comment by Hosq** [comment]
Sync throttling is already handling this problem but it was set to only 1 second on chromaggus. I have changed it to 25 so now it should only accept one sync every 25seconds
