### ISSUE TITLE
Version Query

### ISSUE THREAD

**Issue by Sqoops** [Hosq/BigWigs#20]
Can you add a button to the BigWigs Version Query that, when you click it, whispers everyone in the Raid with an outdated BigWigs Version that there is a new version available at https://github.com/Hosq/BigWigs?
Or instead of whispering everybody could you make that button post all the names of people with an outdated BigWigs Version & the names of people not using BigWigs in the raid chat.

**Comment by Hosq** [comment]
There is now a button to post names of people with old versions to raid chat. You can find it by right clicking the version check window
