### ISSUE TITLE
Your version of Big Wigs Elysium is out of date popup window

### ISSUE THREAD

**Issue by n985950** [Hosq/BigWigs#23]
DCing in the middle of a fight is not a strange thing to happen, and this addon makes the focus of the keyboard be on this textbox in front of your screen. It's horribly annoying and it should be removed entirely from the addon

**Comment by Hosq** [comment]
Have you considered updating when it tells you to?

**Comment by henkethebenke** [comment]
If you have Prat installed you also get a big pop up window in the middle of the screen. This could be solved by removing the URL from the update message. Then you only get a text message.

**Comment by henkethebenke** [comment]
Fixed in #24

**Comment by n985950** [comment]
hey man how do I use this new toggle I can't find it

**Comment by Hosq** [comment]
Plugins -> Version query -> Show popup

**Comment by n985950** [comment]
Big Wigs Elysium (standby): [plugins] is not a valid option for /bw
