### ISSUE TITLE
4H Void Zone timer

### ISSUE THREAD

**Issue by trmptrnick** [Hosq/BigWigs#25]
I'm not exactly sure how these timers work, but after the first zone timer, I do not receive any additional timers pop up. It is super helpful as a healer to see these coming to be able to be in motion when they spawn to avoid damage.

Some additional info: I start in the front left corner of the room where we tank Thane, and move back to the back left corner where we tank Blaumeaux. I'm unsure if it is maybe a proximity thing to see the timers or not. I also turned off some other timers to see if maybe it was just because there was a lot of other things going on since it is a complex fight.

**Comment by dabadoo** [comment]
Same problem.

I only get a warning for the first void zone timer. Meteor and Holy Wrath timers are working fine.

**Comment by Hosq** [comment]
I dont think there is any event showing when the boss actually casts the voidzone so accurate timers after the first one might not be possible.

**Comment by trmptrnick** [comment]
From the WoWWiki page on the original encounter:

Lady Blaumeux (290k HP) — Void Zone 
    Summon a Void Zone that deals shadow damage to enemies that stand within it (approx 3500-4500 damage per tick). Small radius, approximately 5 yards. Persists for 90 seconds when dropped. Range: 45 yards. Cooldown is 12 seconds. Persist after she is killed. 

12 second cooldown on the cast. Even an approximation is better than no warning I think.
