### ISSUE TITLE
BigWigs only shows one Burning Adrenaline at a time for the BWL Vaelastrasz fight

### ISSUE THREAD

**Issue by Textarea-LotC** [Hosq/BigWigs#27]
During the 'Tank Burn' part of the fight, Vael puts 2 burning adrenalines on people. The GUI only shows the tank's name.
https://i.imgur.com/N7r34Do.jpg
We wiped on the attempt before the one in the picture since nobody noticed the burning adrenaline in the group.
(BigWigs r20022)

**Comment by Hosq** [comment]
Should now show timer for both burning targets

**Comment by Textarea-LotC** [comment]
Hi, I just did BWL a few hours ago and I updated my BigWigs right before it.

https://i.imgur.com/PbGd4wg.png (1st Vael attempt)
In this picture, Darkanarc is dead with a timer still on him. Ataxia (tank) got a timer and Icedik (the mage I circled) didn't get a timer.

https://i.imgur.com/VDXD5KF.png (2nd Vael attempt)
In this picture, Docken (tank) got a timer and Otirrub (the warlock I circled) didn't get a timer.

Here are 3 more pictures from the 2nd Vael attempt:
https://i.imgur.com/jQP5oVB.png (0.8s till Tank Burn and a shaman is burning for 5.6s)
https://i.imgur.com/e9pFavs.png (tank is burning, 44s till Tank Burn, and the shaman is burning for 5.1s)
https://i.imgur.com/hvdraaA.png (tank is burning, 44s till Tank Burn, the shaman is dead and his timer disappeared, and the warlock didn't get a timer)
Each picture is (in theory) 0.5s apart from each other. I used HyperCam 2 with recording at 2 fps.

(using Vaelastrasz.lua r20008)

**Comment by Hosq** [comment]
Looked like you were getting syncs from older versions that caused the issue this time so i made a change to only accept syncs from current revision

**Comment by Textarea-LotC** [comment]
It works perfectly now. Thanks!
