### ISSUE TITLE
aq40, aq20 bugreport

### ISSUE THREAD

**Issue by 0ldi** [Hosq/BigWigs#4]
`aq40`
1) The Prophet Skeram
-Split Alert broken
2) Vem, Yauj, Kri
-Fear broken
-Poison Cloud untested
3) Battleguard Sartura
-working
4) Fankriss the Unyielding
-Worm Alert broken
5) Viscidus
-Freezing States Alert (i am not sure, but alerts not in main alert frame)
6) Princess Huhuran
-working
7) Vek'lor, Vek'nilash
-report later
8) Ouro
-report later
9) C'Thun
-report later

`aq20`
1) Kurinnaxx
-working (nothing)
2) General Rajaxx
-working
3) Buru the Gorger
-working
4) Moam
-Paralyze Alert broken (but i am not sure)
5) Ayamiss the Hunter
-working
6) Ossirian the Unscarred
-Debuff Alert broken (but i am not sure)

**Comment by Hosq** [comment]
Fixed all errors i found. 
https://github.com/Hosq/BigWigs/commit/47163544988e2e05c8cd7178b2ed4ecd6df56992

**Comment by 0ldi** [comment]
24.05 there was something wrong with the timers on Chromaggus
Breath timers was late about 5 sec
