### ISSUE TITLE
Ossirian Warstomp timers are off

### ISSUE THREAD

**Issue by Schoof-T** [Hosq/BigWigs#5]
The timer for Ossirian's Warstomp is not working correctly.

The first cast is correctly displayed but after that the timer is set to every 20 seconds while It should be 30 I think.

**Comment by Hosq** [comment]
First warstomp happens exactly 25sec after pull and the rest are 25-35sec. So my 25sec timer is as accurate as it can be.

**Comment by Schoof-T** [comment]
It's random between 25-35 seconds? Didn't know that, my apologies. Thanks :)
