### ISSUE TITLE
Request: automatically make ktm lock on Broodlord and Fankriss in the beginning

### ISSUE THREAD

**Issue by dabadoo** [Hosq/BigWigs#6]
Would it be possible to add automatic ktm lock for the following bosses:

Broodlord Lashlayer: Since there are whelps that need to be killed in the beginning it makes ktm imprecise for Broodlord himself.

Fankriss the Unyielding: A lot of adds spawn throughout the fight, some that need to be nuked. These makes ktm imprecise for the main boss once again.

Btw, Is a specific ktm version needed or should the common KTM 17.35 work?

**Comment by Hosq** [comment]
Added now
