### ISSUE TITLE
Onyxia announces fireball on Phase 2 as a Deepbreath

### ISSUE THREAD

**Issue by tiagones** [Hosq/BigWigs#7]
Since the Elysium team did the last Onyxia update on 05/24/2017, the BigWigs announces Ony fireball as a Deepbreath on Phase 2.

The update regarding the Deepbreath is:
> Onyxia's Deep Breath probability has been adjusted from 33.3% (repeating, of course) to 30%

**Comment by Hosq** [comment]
Havent noticed such thing happening. The deepbreath warning only comes when onyxia emotes "takes in a deep breath" so i dont really see how it would trigger on fireball cast

**Comment by tiagones** [comment]
Hello Hosq, thank you for the reply.

So, this is happening with my guild on Darrowshire, we were short on people and Phase 2 was taking so much time. Everybody on the raid uses this version of Bigwigs (since is so awesome!), and sometimes Bigwigs announces Deep Breath when she casts a Fireball, this caused a few wipes since people was expecting a Breath and stay stacked and multiple players were hit by the fireball.

I turn off manually the Fireball announce for me and had no more problem, this is why I think something is a little funky with the last Ony update.

If you need more info, I'm happy to provide.

**Comment by Hosq** [comment]
Still havent been able to get it to bug out like this and dont see anything in the updates to suggest it could. Try to record it if it happens again

**Comment by tiagones** [comment]
OK, I will try to record on the next reset.

**Comment by tiagones** [comment]
Hello Hosq,

We did Ony yesterday with the latest version (with the last commits) and we don't experience the problems that originated this issue.

Thanks for the support.
