### ISSUE TITLE
[BWL]koKR translation: bug Broodlord & Chromaggus line error

### ISSUE THREAD

**Issue by godtanker** [Hosq/BigWigs#8]
**Chromaggus line error**
http://cafefiles.naver.net/MjAxNzA2MTJfMTM0/MDAxNDk3MjU4ODQwNjE4.sbm78X_ozESSVPUeXPsN3LbB9ug-H7uIovLcinRv9z4g.gxhsREuFhwcPJt8ijrJcz1pMtz_yeNu4v28lXwC4FDkg.JPEG.ll2j/qqq.jpg

**Comment by Hosq** [comment]
Couldnt reproduce that error on chromaggus and didnt notice anything wrong on broodlord. You have english client and latest version of bigwigs?

**Comment by godtanker** [comment]
Always update your Bigwings with koKR translation. koKR client yet.
Broodlord does not work in BWL. Other bosses work normally.
I would like to ask if there is something wrong with my work.
https://docs.google.com/spreadsheets/d/1II24oJbu9j38cDLnx78H0lGLBkEkaXJA3-PJ_LbiWvQ/edit#gid=43819604
---> i am koKR translation done

**Comment by Hosq** [comment]
Well only thing i see is that your "engage_trigger" is still in english cant really say anything about the other translations and im guessing the error on chromaggus is related to "vulnerability_direct_test" translation

**Comment by godtanker** [comment]
ok, so koKR translation.Bigwigs_Chromaggus : cheack plz..
https://docs.google.com/spreadsheets/d/1II24oJbu9j38cDLnx78H0lGLBkEkaXJA3-PJ_LbiWvQ/edit#gid=1083141603

**Comment by Hosq** [comment]
Ye i really cant tell whats wrong there since i dont speak korean
