### ISSUE TITLE
Ouro Submerge Alert dont work

### ISSUE THREAD

**Issue by ghost** [Hosq/BigWigs#9]
hi Hosq, Submerge Alert didn't work in the battle of Ouro last night with the latest version of Bigwigs

**Comment by 0ldi** [comment]
We also did not have a timer before the first two Submerge. After that he appeared, but was inaccurate. This Wednesday, the latest version.

**Comment by ghost** [comment]
When will it be fixed?

**Comment by birdayz** [comment]
Most likely not before we can reproduce it. i tried on my own server, but didnt manage to. on anathema, i had the same issue as well. most likely it is a problem with the submerge detection firing when it shouldnt.
